export const heroes = [
  {
    id: 0,
    heroes_name: "iron man",
    heroesID: "ironman",
    identities: "tony stark",
    desc: "lol",
    big_img: "lol",
    durability: 6,
    energy: 6,
    fighting: 4,
    intelligence: 6,
    speed: 5,
    strength: 6,
    imageSize: {
      big: {
        x: 500,
        y: 469,
      },
    },
  },
  {
    id: 1,
    heroes_name: "spider-man",
    heroesID: "spiderman",
    identities: "peter parker",
    desc: "lol",
    big_img: "lol",
    durability: 3,
    energy: 1,
    fighting: 4,
    intelligence: 4,
    speed: 3,
    strength: 4,
    imageSize: {
      big: {
        x: 500,
        y: 500,
      },
    },
  },
  {
    id: 2,
    heroes_name: "hulk",
    heroesID: "hulk",
    identities: "bruce banner",
    desc: "lol",
    big_img: "lol",
    durability: 7,
    energy: 5,
    fighting: 4,
    intelligence: 6,
    speed: 3,
    strength: 7,
    imageSize: {
      big: {
        x: 820,
        y: 630,
      },
    },
  },
  {
    id: 3,
    heroes_name: "thor",
    heroesID: "thor",
    identities: "thor",
    desc: "lol",
    big_img: "lol",
    durability: 6,
    energy: 6,
    fighting: 4,
    intelligence: 2,
    speed: 7,
    strength: 7,
    imageSize: {
      big: {
        x: 500,
        y: 522,
      },
    },
  },
  {
    id: 4,
    heroes_name: "docteur strange",
    heroesID: "docteurstrange",
    identities: "stephen strange",
    desc: "lol",
    big_img: "lol",
    durability: 3,
    energy: 6,
    fighting: 3,
    intelligence: 4,
    speed: 7,
    strength: 2,
    imageSize: {
      big: {
        x: 820,
        y: 630,
      },
    },
  },
];
