import Head from 'next/head'
import Image from 'next/image'
import Header from "../engine/component/Header/Header";
import styles from "../styles/Home.module.scss";
import Card from "./../engine/component/Card/Card";

export default function Home() {
  return (
    <main className={styles.main}>
      <Head>
        <title>Marvel Heroes</title>
        <meta
          name="description"
          content="Marvel Heroes generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Card />
    </main>
  );
}
